### ISSUE TITLE
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

### ISSUE THREAD

**Issue by k1ng440** [micro/cli#7]
hello
i am getting following error when i use StringSlice()

```
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

goroutine 1 [running]:
github.com/micro/cli.lookupStringSlice(...)
        /e/go/src/github.com/micro/cli/context.go:303
github.com/micro/cli.(*Context).StringSlice(...)
        /e/go/src/github.com/micro/cli/context.go:61
github.com/coinread/microservice.setupConfig(0xc0004ae000)
        /e/go/src/github.com/coinread/microservice/hack.go:41 +0x865
github.com/coinread/microservice.NewService.func1(0xc0004ae000)
        /e/go/src/github.com/coinread/microservice/microservice.go:81 +0x90
github.com/micro/cli.(*App).Run(0xc000376160, 0xc00003a1b0, 0x1, 0x1, 0x0, 0x0)
        /e/go/src/github.com/micro/cli/app.go:202 +0x81f
github.com/micro/cli.(*App).RunAndExitOnError(0xc000376160)
        /e/go/src/github.com/micro/cli/app.go:208 +0x53
github.com/micro/go-micro/cmd.(*cmd).Init(0xc00037a000, 0xc00059f200, 0x5, 0x5, 0x134, 0x135)
        /e/go/src/github.com/micro/go-micro/cmd/cmd.go:462 +0xdf
github.com/micro/go-micro.(*service).Init.func1()
        /e/go/src/github.com/micro/go-micro/service.go:47 +0x127
sync.(*Once).Do(0xc00012e370, 0xc00057dd20)
        /usr/local/go/src/sync/once.go:44 +0xb3
github.com/micro/go-micro.(*service).Init(0xc00012e2a0, 0xc00000e9a0, 0x1, 0x1)
        /e/go/src/github.com/micro/go-micro/service.go:45 +0x8e
github.com/coinread/microservice.NewService(0x11f00f3, 0xa, 0xc00034abf0, 0x0, 0x0, 0x0, 0x27, 0xc00057df88)
        /e/go/src/github.com/coinread/microservice/microservice.go:78 +0x60a
main.main()
        /e/go/src/github.com/coinread/ticker-srv/main.go:27 +0xad
exit status 2
```

**Comment by k1ng440** [comment]
Never mind

i was just using cli.StringFlag in micro.Flags
